title: Mini Saxena
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/">LinkedIn</a> |
  <a href="https://github.com/">GitHub</a>
  
  <br>   
  I am working professional have 10 years of experience
  </p>



theme: jekyll-theme-minimal

